repository:
  name: setting-demo
  description: This is just a demo test
  private: true
  has_issues: false
  has_projects: true
  has_wiki: true
  has_pages: true
  has_downloads: false
  has_discussions: true
  